site_name: GENIUS-LLM Documentation
#site_url: https://yimengzhiyan.github.io/GENIUS-LLM/
#repo_url: https://github.com/yimengzhiyan/GENIUS-LLM  # Required for edit_uri to function
repo_url: https://github.com/ZhengJieBioinformatics/GENIUS-LLM
site_url: https://ZhengJieBioinformatics.github.io/GENIUS-LLM/
site_author: Jie Zheng
repo_name: GENIUS-LLM
edit_uri: edit/main/docs/ # Allows users to click the "Edit" button (promotes open-source collaboration)

theme:
  name: material
  palette:
    primary: teal  # Provides a professional academic aesthetic
    accent: indigo
  features:
    - navigation.tabs          # Top-level navigation categories
    - content.code.copy        # Enables one-click code copying (useful for researchers)
    - navigation.sections      # Groups sidebar items for a clearer structure
    - navigation.expand        # Expands all directories by default for easier navigation
    - navigation.top           # "Back to top" button for long documents
    - navigation.tracking      # Sidebar automatically highlights current position while scrolling
    - search.suggest           # Displays auto-completion suggestions during search
    - search.highlight         # Highlights keywords in search results
    - content.code.annotate    # Enables hover annotations (ideal for explaining complex API calls)
  
  # Set LOGO and Favicon (browser tab icon)
  icon:
    logo: material/dna # Or material/molecule-science
# favicon: assets/favicon.png # Create an 'assets' folder in 'docs/' and add a 'favicon.png' file

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yimengzhiyan
    - icon: fontawesome/solid/paper-plane
      link: mailto:your-email@example.com

markdown_extensions:
  - tables           # Enables table support (necessary for compatibility matrices)
  - admonition       # Enables callouts/admonitions (e.g., !!! note or !!! warning)
  - pymdownx.details # Enables collapsible blocks to save space with long code segments
  - pymdownx.superfences # Allows nesting code blocks within lists
  - pymdownx.magiclink   # Automatically converts URLs into clickable links
  - pymdownx.arithmatex:
      generic: true
  - attr_list        # Allows adding CSS styles to Markdown elements

nav:
  - Home: index.md
  - Installation: 01installation.md
  - Quick Start: 02quickstart.md
  - Configuration Installation: 03configuration.md
  - Model Setup: 04models_setup.md
  - Supported Models list: 05models_list.md