site_name: GENIUS-LLM Documentation
repo_url: https://github.com/ZhengJieBioinformatics/GENIUS-LLM
site_url: https://ZhengJieBioinformatics.github.io/GENIUS-LLM/
site_author: Jie Zheng
repo_name: GENIUS-LLM
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: teal
    accent: indigo
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.annotate
  icon:
    logo: material/dna

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yimengzhiyan
    - icon: fontawesome/solid/paper-plane
      link: mailto:your-email@example.com

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.arithmatex:
      generic: true
  - attr_list

nav:
  - Home: index.md
  - Installation: 01installation.md
  - Quick Start: 02quickstart.md
  - Configuration Installation: 03configuration.md
  - Model Setup: 04models_setup.md
  - Supported Models list: 05models_list.md
