site_name: GENIUS-LLM Documentation
#site_url: https://yimengzhiyan.github.io/GENIUS-LLM/
#repo_url: https://github.com/yimengzhiyan/GENIUS-LLM  # 必须加这一行，edit_uri 才会生效
repo_url: https://github.com/ZhengJieBioinformatics/GENIUS-LLM
site_url: https://ZhengJieBioinformatics.github.io/GENIUS-LLM/
site_author: Jie Zheng
repo_name: GENIUS-LLM
edit_uri: edit/main/docs/ # 允许别人点击“编辑”按钮（展现开源精神）

theme:
  name: material
  palette:
    primary: teal  # 这种青绿色看起来很学术
    accent: indigo
  features:
    - navigation.tabs          # 顶部大分类（你已经选了）
    - content.code.copy    # 增加代码一键复制（对研究人员极其友好）
    - navigation.sections      # 侧边栏分组显示，结构更清晰
    - navigation.expand        # 默认展开所有目录（方便审稿人快速点击）
    - navigation.top           # 快速回到顶部按钮（长文档必备）
    - navigation.tracking      # 滚动时侧边栏自动跟随当前位置
    - search.suggest           # 搜索时显示自动补全建议
    - search.highlight         # 搜索结果关键词高亮
    - content.code.annotate    # 允许在代码中添加悬浮注释（非常适合解释复杂的 API 调用）
  # 设置 LOGO 和 Favicon（浏览器标签页的小图标）
  icon:
    logo: material/dna # 或者 material/molecule-science
 # favicon: assets/favicon.png #在 docs/ 文件夹下创建一个 assets 文件夹，并放一张名为 favicon.png 的小图标。


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yimengzhiyan
    - icon: fontawesome/solid/paper-plane
      link: mailto:your-email@example.com

markdown_extensions:
  - tables          # 开启表格支持（审稿人要求的兼容性矩阵必须用这个）
  - admonition      # 开启警告框/提示框（!!! note 或 !!! warning）
  - pymdownx.details # 开启折叠面板（适合放长代码，不占空间）
  - pymdownx.superfences # 允许在列表里嵌套代码块
  - pymdownx.magiclink   # 自动把 URL 变成可点击链接
  - attr_list       # 允许给 Markdown 元素加 CSS 样式

nav:
  - Home: index.md
  - Installation: 01installation.md
  - Quick Start: 02quickstart.md
  - Configuration Installation: 03configuration.md
  - Model Setup: 04models_setup.md
  - Supported Models list: 05models_list.md



