model:
  url: https://api.deepseek.com
  api_key: sk- # replace your api_key
  model: deepseek-chat

mongodb:
  uri: "mongodb://localhost:27017/"
  database: "arabidopsis_gene_db" # Database names for corresponding species (need to be changed)

# for 01process_data.py 
## Defined the input and output file paths for each data type for data processing operations.
data_paths:
  blast:
    input: "src/data/yourdata_process/01gene_blast.txt"
    output: "src/data/yourdata_process_output/blast_results_text.txt"
  coexpression:
    input: "src/data/yourdata_process/02cultivar"
    output: "src/data/yourdata_process_output/coexpression_output.txt"
  expression:
    input: "src/data/yourdata_process/03all_Tissue_mean_TPM.csv"
    output: "src/data/yourdata_process_output/expression_output.txt"
  homolog:
    input: "src/data/yourdata_process/04multi_gene_data.xlsx"
    output: "src/data/yourdata_process_output/homolog_output.txt"
  twas:
    input: "src/data/yourdata_process/05TWAS_out_240925.xlsx"
    output: "src/data/yourdata_process_output/twas_output.txt"
  kegg:
    input: "src/data/yourdata_process/06KEGG.csv"
    output: "src/data/yourdata_process_output/KEGG_descriptions.txt"
  go:
    input: "src/data/yourdata_process/07GO.csv"
    output: "src/data/yourdata_process_output/GO_descriptions.txt"

# for 02import_data.py
  ## Defined the various data sources to be imported into the MongoDB database and the target collections.
  ## Currently supports TXT and CSV files
data_imports:
  blast:
    input_path: "src/data/yourdata_process_output/blast_results_text.txt"  # Read the gene alignment data from the file "src/data/test_import/01gene_blast_cleaned.txt" and import it into the MongoDB collection.
    collection: "gene_blast_similarity"
  coexpression:
    input_path: "src/data/yourdata_process_output/coexpression_output.txt"
    collection: "gene_coexpression"
  expression:
    input_path: "src/data/yourdata_process_output/expression_output.txt"
    collection: "gene_expression"
  homolog:
    input_path: "src/data/yourdata_process_output/homolog_output.txt"
    collection: "homologous_genes"
  twas:
    input_path: "src/data/yourdata_process_output/twas_output.txt"
    collection: "gene_trait_twas"
  kegg:
    input_path: "src/data/yourdata_process_output/KEGG_descriptions.txt" # Import the KEGG database
    collection: "kegg_pathways"
  go:
    input_path: "src/data/yourdata_process_output/GO_descriptions.txt" # Import the GO database
    collection: "go_terms"




common:
  log_path: "logs/"
  threshold:
    blast:
      similarity: 0.9
      e_value: 1e-5
    coexpression:
      weight: 0.9
    twas:
      zscore: 2.0